.PHONY: clean All

All:
	@echo "----------Building project:[ hw14 - Debug ]----------"
	@"$(MAKE)" -f  "hw14.mk"
clean:
	@echo "----------Cleaning project:[ hw14 - Debug ]----------"
	@"$(MAKE)" -f  "hw14.mk" clean
