#!/bin/bash
gcc -std=c99 -Wall -Wshadow -Wvla -pedantic -g -lm *.c -o pa1
valgrind pa1 original/gophers gophers.count gophers.tree gophers.code gophers.hbt
diff gophers.count count/gophers.count
diff gophers.tree tree/gophers.tree
diff gophers.code code/gophers.code
diff gophers.hbt compressed/gophers.hbt

valgrind pa1 original/lorum lorum.count lorum.tree lorum.code lorum.hbt
diff lorum.count count/lorum.count
diff lorum.tree tree/lorum.tree
diff lorum.code code/lorum.code
diff lorum.hbt code/lorum.hbt

valgrind pa1 original/binary1 binary1.count binary1.tree binary1.code binary1.hbt
diff binary1.count count/binary1.count
diff binary1.tree tree/binary1.tree
diff binary1.code code/binary1.code
diff binary1.hbt compressed/binary1.hbt

valgrind pa1 original/stone stone.count stone.tree stone.code stone.hbt
diff stone.count count/stone.count
diff stone.tree tree/stone.tree
diff stone.code code/stone.code
diff stone.hbt compressed/stone.hbt

valgrind pa1 original/woods woods.count woods.tree woods.code woods.hbt
diff woods.count count/woods.count
diff woods.tree tree/woods.tree
diff woods.code code/woods.code
diff woods.hbt compressed/woods.hbt
